import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

// import css
// import "./globals.css";
import "../sass/main.scss";

// import Components
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";

import { getGlobalSettings } from "@/data/loaders";
import { notFound } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function loader() {
  // destructure the data
  const { data } = await getGlobalSettings();
  // console.log(data);
  // console.dir(data, { depth: null });
  // if (!data) throw new Error("Failed to fetch global settings");
  if (!data) notFound();

  return { header: data?.header, footer: data?.footer };
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Destructure Loader
  const { header, footer } = await loader();

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header data={header} />
        {children}
        <Footer data={footer} />
      </body>
    </html>
  );
}
